server:
  port: 9000
---
spring:
  application:
    name: say-hello

application:
  message: Hello, Kevin

say-hello:
  ribbon:
    eureka:
      enabled: true
    listOfServers: localhost:9000,localhost:9092,localhost:9999
    ServerListRefreshInterval: 15000